export const typeLabelToImgMapping: { [key: string]: string } = {
  normal: "/images/pokeType/normal.png",
  fire: "/images/pokeType/fire.png",
  water: "/images/pokeType/water.png",
  grass: "/images/pokeType/grass.png",
  electric: "/images/pokeType/electric.png",
  ice: "/images/pokeType/ice.png",
  fighting: "/images/pokeType/fighting.png",
  poison: "/images/pokeType/poison.png",
  ground: "/images/pokeType/ground.png",
  flying: "/images/pokeType/flying.png",
  psychic: "/images/pokeType/psychic.png",
  bug: "/images/pokeType/bug.png",
  rock: "/images/pokeType/rock.png",
  ghost: "/images/pokeType/ghost.png",
  dragon: "/images/pokeType/dragon.png",
  dark: "/images/pokeType/dark.png",
  steel: "/images/pokeType/steel.png",
  fairy: "/images/pokeType/fairy.png",
};

export const typeLabelToColor: { [key: string]: string } = {
  normal: "#A8A77A",
  fire: "#EE8130",
  water: "#6390F0",
  grass: "#7AC74C",
  electric: "#F7D02C",
  ice: "#96D9D6",
  fighting: "#C22E28",
  poison: "#A33EA1",
  ground: "#E2BF65",
  flying: "#6390F0",
  psychic: "#F95587",
  bug: "#A6B91A",
  rock: "#B6A136",
  ghost: "#735797",
  dragon: "#6F35FC",
  dark: "#705746",
  steel: "#B7B7CE",
  fairy: "#D685AD",
};
